LeadTheWay/Areas/Admin/Controllers/MapsManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using LeadTheWay.Areas.Admin.Models.DTOs;
using LeadTheWay.Data;
using LeadTheWay.GraphLayer.Link.Domain.Models;
using LeadTheWay.GraphLayer.Map.Domain.Models;
using LeadTheWay.GraphLayer.Map.Service;
using LeadTheWay.GraphLayer.Vertex.Service;
using LeadTheWay.Models.ViewModels;
using LeadTheWay.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LeadTheWay.Areas.Admin.Controllers
{
    [Authorize(Roles = StaticDetails.AdminUser)]
    [Area("Admin")]
    public class MapsManagementController : Controller
    {
        private readonly ApplicationDbContext db;

        [BindProperty]
        public GraphMapViewModel GraphMapVM { get; set; }


        public MapsManagementController(ApplicationDbContext db)
        {
            this.db = db;

            GraphMapVM = new GraphMapViewModel()
            {
                GraphMap = new GraphMap(),
                Edges = db.IntercityLinks.ToList()
            };
            GraphMapVM.GraphMap.Graph = new Graph();
            //GraphMapVM.GraphMap.CurrentEdgeIdToAdd = 0; ///TODO: ?
        }


        // GET: MapsManagement
        public IActionResult Index()
        {
            return View(db.GraphMaps.ToList());
        }

        // GET: MapsManagement/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MapsManagement/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SimpleGraph graphDTO)
        {
            if (ModelState.IsValid)
            {
                var graph = new GraphMap()
                {
                    Name = graphDTO.Name,
                    IsDefault = graphDTO.IsDefault,
                    NodeHistory = new List<string>(),
                    EdgeHistory = new List<string>()
                };
                db.Add(graph);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(graphDTO);
        }

        // GET: MapsManagement/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var graph = await db.GraphMaps.FindAsync(id);

            if (graph == null)
            {
                return NotFound();
            }

            //test
            graph.GraphString = graph.GraphString ?? string.Empty;
            graph.Graph = graph.Graph ?? new Graph();
            graph.NodeHistoryString = graph.NodeHistoryString ?? string.Empty;
            graph.NodeHistory = graph.NodeHistory ?? new List<string>();
            graph.EdgeHistoryString = graph.EdgeHistoryString ?? string.Empty;
            graph.EdgeHistory = graph.EdgeHistory ?? new List<string>();
            //end of test

            GraphMapVM.GraphMap = graph;

            return View(GraphMapVM);
        }

        // POST: MapsManagement/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id)
        {
            if (id != GraphMapVM.GraphMap.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var edge = await db.IntercityLinks.Where(e => e.Id == GraphMapVM.GraphMap.CurrentEdgeIdToAdd).FirstOrDefaultAsync();

                bool isNotDirected = edge.EdgeString.Contains("<->");
                var nodes = isNotDirected ? edge.EdgeString.Split(new string[] { "<->" }, StringSplitOptions.None) : edge.EdgeString.Split(new string[] { "->" }, StringSplitOptions.None);
                edge.NodesPair = new VerticesPair
                {
                    FirstNodeId = (await db.TransportVertices.Where(n => n.Name == nodes[0]).FirstOrDefaultAsync()).Id,
                    RelatedNodeId = (await db.TransportVertices.Where(n => n.Name == nodes[1]).FirstOrDefaultAsync()).Id
                };

                var firstNode = await db.TransportVertices.Where(n => n.Id == edge.NodesPair.FirstNodeId).FirstOrDefaultAsync();
                var relatedNode = await db.TransportVertices.Where(n => n.Id == edge.NodesPair.RelatedNodeId).FirstOrDefaultAsync();

                var graph = GraphMapVM.GraphMap;

                graph.GraphString = graph.GraphString ?? string.Empty;
                graph.Graph = graph.Graph ?? new Graph();
                graph.NodeHistoryString = graph.NodeHistoryString ?? string.Empty;
                graph.NodeHistory = graph.NodeHistory ?? new List<string>();
                graph.EdgeHistoryString = graph.EdgeHistoryString ?? string.Empty;
                graph.EdgeHistory = graph.EdgeHistory ?? new List<string>();


                if (!GraphMapVM.GraphMap.NodeHistory.Exists(n => string.Equals(n, firstNode.Name)))
                {
                    bool isEmpty = GraphMapVM.GraphMap.NodeHistory.Count == 0;
                    GraphMapVM.GraphMap.NodeHistory.Add(firstNode.Name);
                    string appendixString = isEmpty ? firstNode.Name : $", {firstNode.Name}";
                    GraphMapVM.GraphMap.NodeHistoryString += appendixString;

                    GraphMapVM.GraphMap.Graph.AddNode(new Node(firstNode.Name, firstNode.Description));
                }

                if (!GraphMapVM.GraphMap.NodeHistory.Exists(n => string.Equals(n, relatedNode.Name)))
                {
                    bool isEmpty = GraphMapVM.GraphMap.NodeHistory.Count == 0;
                    GraphMapVM.GraphMap.NodeHistory.Add(relatedNode.Name);
                    string appendixString = isEmpty ? relatedNode.Name : $", {relatedNode.Name}";
                    GraphMapVM.GraphMap.NodeHistoryString += appendixString;

                    GraphMapVM.GraphMap.Graph.AddNode(new Node(relatedNode.Name, relatedNode.Description));
                }

                if (!GraphMapVM.GraphMap.EdgeHistory.Exists(e => string.Equals(e, edge.EdgeString))) ///TODO: Update direction only if edge exists with different direction (isNotDirected flag)
                {
                    bool isEmpty = GraphMapVM.GraphMap.EdgeHistory.Count == 0;
                    GraphMapVM.GraphMap.EdgeHistory.Add(edge.EdgeString);
                    string appendixString = isEmpty ? edge.EdgeString : $", {edge.EdgeString}";
                    GraphMapVM.GraphMap.EdgeHistoryString += appendixString;
                }

                ///TODO: create EdgeHistoryString from EdgeHistory then create the GraphString and update
                if (isNotDirected)
                {
                    GraphMapVM.GraphMap.Graph.AddBidirectionalEdge(firstNode.Name, relatedNode.Name, edge.Length, TimeSpan.FromTicks(edge.DurationTicks), edge.Price, edge.ServiceClass, null); ///TODO TimetableString to Timetable object
                }
                else
                {
                    GraphMapVM.GraphMap.Graph.AddEdge(firstNode.Name, relatedNode.Name, edge.Length, TimeSpan.FromTicks(edge.DurationTicks), edge.Price, edge.ServiceClass, null); ///TODO TimetableString to Timetable object
                }

                if (!GraphMapVM.GraphMap.Graph.Err)
                {
                    var mapDB = await db.GraphMaps.Where(m => m.Name == GraphMapVM.GraphMap.Name).FirstOrDefaultAsync();

                    mapDB.NodeHistoryString = mapDB.NodeHistoryString ?? string.Empty;

                    var vertices = Regex.Replace(GraphMapVM.GraphMap.NodeHistoryString, @"\s+", string.Empty).Split(',');
                    if (!vertices.Any(mapDB.NodeHistoryString.Contains))
                    {
                        mapDB.NodeHistoryString += string.IsNullOrWhiteSpace(mapDB.NodeHistoryString) ? GraphMapVM.GraphMap.NodeHistoryString : $", { GraphMapVM.GraphMap.NodeHistoryString }";
                    }
                    else if (!vertices.All(mapDB.NodeHistoryString.Contains))
                    {
                        foreach (var vertex in vertices)
                        {
                            if (!mapDB.NodeHistoryString.Contains(vertex))
                            {
                                mapDB.NodeHistoryString += $", {vertex}";
                            }
                        }
                    }

                    mapDB.EdgeHistoryString += string.IsNullOrWhiteSpace(mapDB.EdgeHistoryString) ? GraphMapVM.GraphMap.EdgeHistoryString : $", {GraphMapVM.GraphMap.EdgeHistoryString}";

                    ///                    //
                    //tests
                    ///TODO: GraphString = Graph to string
                    string ns = string.Empty;
                    foreach (var nodeName in Regex.Replace(mapDB.NodeHistoryString, @"\s+", string.Empty).Split(','))
                    {
                        if (GraphMapVM.GraphMap.Graph.Map.TryGetValue(nodeName, out var node))
                        {
                            ns += $"*{nodeName}({node.Description})";
                        }
                    }

                    string es = string.Empty;
                    //foreach (var item in GraphMapVM.GraphMap.EdgeHistory)
                    //{
                    //    var tempEdge = await db.IntercityLinks.Where(e => e.EdgeString == item).FirstOrDefaultAsync();
                    //    es += $"#{item}({tempEdge.Length}, {tempEdge.DurationTicks}, {tempEdge.Price}, {tempEdge.ServiceClass})";
                    //}
                    foreach (var item in GraphMapVM.GraphMap.EdgeHistory)
                    {
                        var tempEdge = await db.IntercityLinks.Where(e => e.EdgeString == item).FirstOrDefaultAsync();

LeadTheWay/Areas/Admin/Views/MapsManagement/Create.cshtml
@model LeadTheWay.Areas.Admin.Models.DTOs.SimpleGraph

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>GraphMap</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsDefault" /> @Html.DisplayNameFor(model => model.IsDefault)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LeadTheWay/Areas/Admin/Views/MapsManagement/Delete.cshtml
@model LeadTheWay.GraphLayer.Map.Domain.Models.GraphMap

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GraphMap</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            Graph-to-String
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GraphString)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDefault)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDefault)
        </dd>
        <dt>
            Node History String
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NodeHistoryString)
        </dd>
        <dt>
            Edge History String
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EdgeHistoryString)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LeadTheWay/Areas/Admin/Views/MapsManagement/Details.cshtml
@model LeadTheWay.GraphLayer.Map.Domain.Models.GraphMap

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Train Station Map (Graph) Data</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            Graph-to-String
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GraphString)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDefault)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDefault)
        </dd>
        <dt>
            Node History String
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NodeHistoryString)
        </dd>
        <dt>
            Edge History String
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EdgeHistoryString)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

LeadTheWay/Areas/Admin/Views/MapsManagement/Edit.cshtml
@using LeadTheWay.Extensions

@model LeadTheWay.Models.ViewModels.GraphMapViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>Train Station Map (Graph) Data</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GraphMap.Id" />
            <div class="form-group">
                <label asp-for="GraphMap.Name" class="control-label"></label>
                <input asp-for="GraphMap.Name" class="form-control" />
                <span asp-validation-for="GraphMap.Name" class="text-danger"></span>
            </div>
            <div class="form-group col-xs-4">
                <label asp-for="Edges" class="sr-only"></label>
                <select asp-for="@Model.GraphMap.CurrentEdgeIdToAdd" asp-items='Model.Edges.ToSelectListItem(Model.GraphMap.CurrentEdgeIdToAdd, "EdgeString")' class="form-control input-group-lg"></select>
            </div><br /><br /><br />
            <div class="form-group">
                <label asp-for="GraphMap.GraphString" class="control-label">Graph-to-String:</label>
                @*<input asp-for="GraphMap.GraphString" readonly  class="form-control" />*@
                @Html.DisplayFor(model => model.GraphMap.GraphString)
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="GraphMap.IsDefault" /> @Html.DisplayNameFor(model => model.GraphMap.IsDefault)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="GraphMap.NodeHistoryString" class="control-label">Node History String</label>
                @*<input asp-for="GraphMap.NodeHistoryString" class="form-control" />*@
                @Html.DisplayFor(model => model.GraphMap.NodeHistoryString)
            </div>
            <div class="form-group">
                <label asp-for="GraphMap.EdgeHistoryString" class="control-label">Edge History String</label>
                @*<input asp-for="GraphMap.EdgeHistoryString" class="form-control" />*@
                @Html.DisplayFor(model => model.GraphMap.EdgeHistoryString)
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LeadTheWay/Areas/Admin/Views/MapsManagement/Index.cshtml
@model IEnumerable<LeadTheWay.GraphLayer.Map.Domain.Models.GraphMap>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Train Station Maps/Modes (Graph Structures)</h2>

@if (Model == null)
{
    <h3>There are no maps in the DB.</h3>
}


<p>
    <a class="nav-link" asp-area="Admin" asp-controller="MapsManagement" asp-action="Create">Create New Map (Graph)</a>
</p>

<table class="table table-striped border">
    <thead>
        <tr class="table-info">
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Graph-to-String
            </th>
            <th>
                Default
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if (item.IsDefault)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GraphString)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsDefault)
                    </td>
                    <td>
                        <partial name="_TableButtonPartial" model="item.Id" />
                    </td>
                </tr>
            }
        }
    </tbody>
</table>