LeadTheWay/Areas/Admin/Controllers/EdgesController.cs
using System.Linq;
using System.Threading.Tasks;
using LeadTheWay.Data;
using LeadTheWay.GraphLayer.Link.Domain.Models;
using LeadTheWay.Models.ViewModels;
using LeadTheWay.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LeadTheWay.Areas.Admin.Controllers
{
    [Authorize(Roles = StaticDetails.AdminUser)]
    [Area("Admin")]
    public class EdgesController : Controller
    {
        private readonly ApplicationDbContext db;

        [BindProperty]
        public EdgeViewModel EdgeVM { get; set; }


        public EdgesController(ApplicationDbContext db)
        {
            this.db = db;

            EdgeVM = new EdgeViewModel()
            {
                Edge = new IntercityLink(),
                Nodes = db.TransportVertices.ToList()
            };
            EdgeVM.Edge.NodesPair = new VerticesPair();
        }


        // GET: Edges
        public IActionResult Index()
        {
            return View(db.IntercityLinks.ToList());
        }

        // GET: Edges/Create
        public IActionResult Create()
        {
            return View(EdgeVM);
        }

        // POST: Edges/Create
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePost()
        {
            var edge = EdgeVM.Edge;
            var firstNode = await db.TransportVertices.Where(n => n.Id == edge.NodesPair.FirstNodeId).FirstOrDefaultAsync();
            var relatedNode = await db.TransportVertices.Where(n => n.Id == edge.NodesPair.RelatedNodeId).FirstOrDefaultAsync();
            string isDirected = EdgeVM.IsDirected ? "->" : "<->";

            edge.EdgeString = $"{firstNode.Name}{isDirected}{relatedNode.Name}";

            edge.DurationTicks = EdgeVM.DurationSpan.Ticks;

            db.IntercityLinks.Add(edge);
            await db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // GET: Edges/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var edge = await db.IntercityLinks.FindAsync(id);

            if (edge == null)
            {
                return NotFound();
            }

            return View(edge);
        }

        // POST: Edges/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, IntercityLink edge)
        {
            if (id != edge.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                ///TODO: Update the EdgeString as well!!! (GraphString not updating after Update Edge)
                db.Update(edge);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(edge);
        }

        // GET: Edges/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var edge = await db.IntercityLinks.FindAsync(id);

            if (edge == null)
            {
                return NotFound();
            }

            return View(edge);
        }

        // GET: Edges/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var edge = await db.IntercityLinks.FindAsync(id);

            if (edge == null)
            {
                return NotFound();
            }

            return View(edge);
        }

        // POST: Edges/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var edge = await db.IntercityLinks.FindAsync(id);
            db.IntercityLinks.Remove(edge);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

LeadTheWay/Areas/Admin/Controllers/NodesController.cs
using System.Linq;
using System.Threading.Tasks;
using LeadTheWay.Data;
using LeadTheWay.GraphLayer.Vertex.Domain.Models;
using LeadTheWay.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LeadTheWay.Areas.Admin.Controllers
{
    [Authorize(Roles = StaticDetails.AdminUser)]
    [Area("Admin")]
    public class NodesController : Controller
    {
        private readonly ApplicationDbContext db;

        public NodesController(ApplicationDbContext db)
        {
            this.db = db;
        }


        //GET: Nodes
        public IActionResult Index()
        {
            return View(db.TransportVertices.ToList());
        }

        // GET: Nodes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Nodes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TransportVertex node)
        {
            if (ModelState.IsValid)
            {
                db.Add(node);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(node);
        }

        // GET: Nodes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var node = await db.TransportVertices.FindAsync(id);

            if (node == null)
            {
                return NotFound();
            }

            return View(node);
        }

        // POST: Nodes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, TransportVertex node)
        {
            if (id != node.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                db.Update(node);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(node);
        }

        // GET: Nodes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var node = await db.TransportVertices.FindAsync(id);

            if (node == null)
            {
                return NotFound();
            }

            return View(node);
        }

        // GET: Nodes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var node = await db.TransportVertices.FindAsync(id);

            if (node == null)
            {
                return NotFound();
            }

            return View(node);
        }

        // POST: Nodes/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var node = await db.TransportVertices.FindAsync(id);
            db.TransportVertices.Remove(node);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

LeadTheWay/Areas/User/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using LeadTheWay.Data;
using LeadTheWay.GraphLayer.Map.Service;
using LeadTheWay.GraphLayer.Map.Service.Search.Services;
using LeadTheWay.GraphLayer.Map.Service.Search.Services.Utility;
using LeadTheWay.GraphLayer.Vertex.Service;
using LeadTheWay.Models;
using LeadTheWay.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LeadTheWay.Areas.User.Controllers
{
    //[Authorize(Roles = StaticDetails.AdminUser + ", " + StaticDetails.EndUser)]
    [Area("User")]
    public class MapController : Controller
    {
        private readonly ApplicationDbContext db;

        private readonly UserManager<IdentityUser> identityUserManager;

        [BindProperty]
        public MapServiceViewModel MapVM { get; set; }

        public MapController(ApplicationDbContext db, UserManager<IdentityUser> identityUserManager)
        {
            this.db = db;
            this.identityUserManager = identityUserManager;
            MapVM = new MapServiceViewModel();
        }

        // GET: Map
        public async Task<IActionResult> Index()
        {
            ///TODO:
            //var result = Graph.Search(new CheapestPathSearch(user.Map.Graph), "Plovdiv", "Varna");
            //var cheapest = GraphUtil.ResultCheapest;
            //cheapest += result + '\n';

            MapVM.User = await GetApplicationUserWithDefaultGraphMapFromClaimsPrincipalUser(User);

            ///TODO: To check if the departure/arrival names are set and to display the algorithm results

            return View(MapVM);
        }

        // POST: Map
        [HttpPost, ActionName("Index")]
        public async Task<IActionResult> IndexPost()
        {
            MapVM.User = await GetApplicationUserWithDefaultGraphMapFromClaimsPrincipalUser(User);

            string result = string.Empty;
            if (!string.IsNullOrEmpty(MapVM.IntermediatePlace))
            {
                result = Graph.Search(
                    new PathWithIntermediatePointsSearch(MapVM.User.Map.Graph),
                    MapVM.DeparturePlace,
                    MapVM.ArrivalPlace,
                    new List<Node>() { MapVM.User.Map.Graph.GetNodeByName(MapVM.IntermediatePlace) });
            }
            else if (MapVM.DeparturePlace != null && MapVM.ArrivalPlace != null)
            {
                result = Graph.Search(new CheapestPathSearch(MapVM.User.Map.Graph), MapVM.DeparturePlace, MapVM.ArrivalPlace);
            }

            GraphUtil.ResultCheapest += result;
            MapVM.Path = GraphUtil.ResultCheapest;

            //var region = new List<string>() { "Varna", "Plovdiv|" };
            //int from = MapVM.Path.IndexOf(region[0]) + region[0].Length;
            //int to = MapVM.Path.LastIndexOf(region[1]);
            //MapVM.PathShort = MapVM.Path.Substring(from, to - from);

            var sub = MapVM.Path.Substring(MapVM.Path.LastIndexOf("Cost"));
            sub = sub.Substring(sub.IndexOf("\n") + "\n".Length).Split("\n".ToCharArray()).First();
            sub = sub.Remove(sub.Length - 1);
            var split = sub.Split(new string[] { "<-" }, StringSplitOptions.None).ToList();
            split.Reverse();
            MapVM.PathShort = string.Join("->", split.ToArray());
            var stations = new List<Node>();
            foreach (var townName in split)
            {
                stations.Add(MapVM.User.Map.Graph.GetNodeByName(townName));
            }

            double sum = 0;
            for (int i = 0; i < stations.Count - 1; i++)
            {
                foreach (var link in stations[i].Edges)
                {
                    if (link.RelatedNode.Name.Equals(stations[i + 1].Name))
                    {
                        sum += link.Price;
                    }
                }
            }

            MapVM.PathPrice = Math.Round(sum, 2);
            MapVM.PathLength = stations[stations.Count - 1].CurrentLength;

            return View(MapVM);
        }

        private async Task<ApplicationUser> GetApplicationUserWithDefaultGraphMapFromClaimsPrincipalUser(System.Security.Claims.ClaimsPrincipal userPrincipal)
        {
            var identityUser = await identityUserManager.GetUserAsync(userPrincipal);

            var user = await db.ApplicationUsers.Where(u => u.UserName == identityUser.UserName).FirstOrDefaultAsync();
            user.Map = db.GraphMaps.Where(m => m.IsDefault).FirstOrDefault();
            user.Map.Graph = new Graph
            {
                Id = user.Map.Id,
                Name = user.Map.Name,
                GraphString = user.Map.GraphString
            };
            ///TODO: Iitialize user.Map.Graph.Map Dictionary with Name, Node
            var lines = Regex.Split(user.Map.Graph.GraphString, @"(?=[*#])").Where(line => !string.IsNullOrEmpty(line)).ToArray();
            foreach (var line in lines)
            {
                var tempLine = line.Substring(1, line.Length - 1);
                switch (line[0])
                {
                    case '*':
                        Node node;
                        if (tempLine.Contains('('))
                        {
                            var nodeParts = tempLine.Split("(", 2);
                            node = new Node(nodeParts[0], nodeParts[1].Remove(nodeParts[1].Length - 1));
                        }
                        else
                        {
                            node = new Node(tempLine);
                        }

                        user.Map.Graph.AddNode(node);
                        break;
                    case '#':
                        var edgeParts = tempLine.Split("(", 2);
                        var nodes = edgeParts[0].Split(edgeParts.Contains("<->") ? "<->" : "->");
                        ///TODO: Edge string -> Graph add edge
                        var values = edgeParts[1].Remove(edgeParts[1].Length - 1)
                            .Split(',').Select(value => value.Trim())
                            .Where(value => !string.IsNullOrWhiteSpace(value)).ToArray();

                        user.Map.Graph.AddEdge(nodes[0], nodes[1], double.Parse(values[0]), TimeSpan.FromTicks(long.Parse(values[1])), double.Parse(values[2]), byte.Parse(values[3]), null);
                        break;
                }
            }

            return user;
        }
    }
}

LeadTheWay/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using LeadTheWay.Extensions
@using LeadTheWay.Utility

@inject IHttpContextAccessor httpContextAccessor


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LeadTheWay</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">LeadTheWay</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole(StaticDetails.EndUser) || User.IsInRole(StaticDetails.AdminUser))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="User" asp-controller="Map" asp-action="Index">Let Me Lead The Way</a>
                        </li>
                    }
                    @if (User.IsInRole(StaticDetails.AdminUser))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="UsersManagement" asp-action="Index">Manage Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="MapsManagement" asp-action="Index">Map Management</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Nodes" asp-action="Index">Node Management</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Edges" asp-action="Index">Edge Management</a>
                        </li>
                    }
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - LeadTheWay</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

LeadTheWay/Views/Shared/_Layout2.cshtml
@using Microsoft.AspNetCore.Http
@using LeadTheWay.Extensions
@using LeadTheWay.Utility

@inject IHttpContextAccessor httpContextAccessor


<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - LeadTheWay</title>

        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        </environment>
        <style>
            body, html {
              height: 100%;
              margin: 0;
              font: 400 15px/1.8 "Lato", sans-serif;
              color: #777;
            }

            .bgimg-1, .bgimg-2, .bgimg-3 {
              position: relative;
              opacity: 0.65;
              background-attachment: fixed;
              background-position: center;
              background-repeat: no-repeat;
              background-size: cover;
            }
            .bgimg-1 {
              padding-bottom: 350px;
              padding-top: 350px;
              min-height: 100%;
            }

            .bgimg-2 {
              background-image: url("img_parallax2.jpg");
              min-height: 700px;
            }

            .bgimg-3 {
              background-image: url("img_parallax3.jpg");
              min-height: 800px;
            }

            .caption {
              position: absolute;
              left: 0;
              top: 50%;
              width: 100%;
              text-align: center;
              color: #000;
            }

            .caption span.border {
              background-color: #111;
              color: #fff;
              padding: 18px;
              font-size: 25px;
              letter-spacing: 10px;
            }

            h3 {
              letter-spacing: 5px;
              text-transform: uppercase;
              font: 20px "Lato", sans-serif;
              color: #111;
            }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">LeadTheWay</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @if (User.IsInRole(StaticDetails.EndUser) || User.IsInRole(StaticDetails.AdminUser))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="User" asp-controller="Map" asp-action="Index">Let Me Lead The Way</a>
                            </li>
                        }
                        @if (User.IsInRole(StaticDetails.AdminUser))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="UsersManagement" asp-action="Index">Manage Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="MapsManagement" asp-action="Index">Map Management</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="Nodes" asp-action="Index">Node Management</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="Edges" asp-action="Index">Edge Management</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>

        <partial name="_CookieConsentPartial" />

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2019 - LeadTheWay</p>
            </footer>
        </div>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("Scripts", required: false)
    </body>
</html>

LeadTheWay/Views/Shared/_TableButtonPartial.cshtml
@model int

<td style="width:150px">
    <div class="btn-group" role="group">
        <a class="btn btn-primary" href="@Url.Action($"Edit/{Model}")">
            <i class="fas fa-edit"></i>
        </a>
        <a class="btn btn-success" href="@Url.Action($"Details/{Model}")">
            <i class="fas fa-th-list"></i>
        </a>
        <a class="btn btn-danger" href="@Url.Action($"Delete/{Model}")">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>